eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${eureka.instance.hostname}:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  read-timeout: 5000
  connect-timeout: 5000
authserver:
  hostname: localhost
  port: 5000
  contextPath: /uaa
spring:
  security:
    oauth2:
      resource:
        user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/user
        prefer-token-info: false
      client:
        access-token-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
        user-authorization-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/authorize
        client-id: clinet_2