server:
  port: 8888
spring:
  application:
    name: jbm-config
  profiles:
    active: native
    cloud:
    config:
      server:
        native:
          search-locations: classpath:/native,file:native/
  security:
    user:
      name: config
      password: password