server:
  port: 8761
spring:
  application:
    name: jbm-registry
eureka:
  server:
    enable-self-preservation: false
  instance:
    #    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
  client:
    register-with-eureka: false
    fetch-registry: false
