server:
  port: 8761
spring:
  application:
    name: jbm-registry
eureka:
  server:
    enable-self-preservation: false
  instance:
    #    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
